all: QuickSort InputFileGenerator

QuickSort: QuickSort.cpp
	g++ -o QuickSort QuickSort.cpp

InputFileGenerator: InputFileGenerator.cpp
	g++ -o InputFileGenerator InputFileGenerator.cpp

clean:
	rm -f QuickSort InputFileGenerator input_* output_* *.txt
	
